#!/usr/bin/env bash
trap 'kill $(jobs -p)' SIGINT
trap 'nginx -s stop' SIGINT

shift
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null
set -o errexit
set -o nounset

# Run with FAKE_DATA=True to fake the data
FAKE_DATA=${FAKE_DATA:-False}

# Override if we detect the wrong PLATFORM
PLATFORM=${PLATFORM:-$(./dev/scripts/platform)}

# Override if our mac detection fails
MAC=${MAC:-$(./dev/scripts/get-mac-address)}

export FAKE_DATA PLATFORM MAC

echo "starting the web server"; (
  nginx -p . -c dev/nginx.conf &
) &

if [[ ! -d venv ]]; then
  python3 -m venv venv
fi

echo "starting the api"; (
  # shellcheck source=/dev/null
  . venv/bin/activate
  python3 -m src.api.api
) &

echo "starting the data logger"; (
  # shellcheck source=/dev/null
  . venv/bin/activate
  python3 -m src.datalogger.csv_datalogger
) &

echo "starting the protocol"; (
  # shellcheck source=/dev/null
  . venv/bin/activate
  python3 -m src.protocol.run
)
