#!/bin/bash
set -e

unattended=$(echo $* | grep --quiet -- '--yes' && echo yes || true)
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

prompt() {
  if [[ "$unattended" != "yes" ]]; then
    read -p "$* (y/N)" confirm && \
      [[ $confirm == [yY] || $confirm == [yY][eE][sS ]] \
      || exit 1
  fi
}

Clear='\033[0m' # No Color
Green='\033[0;32m'
Blue='\033[0;34m'

help() {
  echo -e "$(
  cat << HELP

  ☀️ solar-protocol - commandline tool to help manage your server

  ${Green}start the server:

    ${Blue}solar-protocol up

  ${Green}check the api logs:

    ${Blue}solar-protocol logs api

  ${Green}start in dev mode with live code reloading:

    ${Blue}solar-protocol dev

  ${Green}check status of the containers:

    ${Blue}solar-protocol status

  ${Green}restart the datalogger:

    ${Blue}solar-protocol restart datalogger

  ${Green}stop the server:

    ${Blue}solar-protocol down

  ${Green}open a shell in the protocol container:

    ${Blue}solar-protocol shell protocol${Clear}
HELP
)"
  exit
}

compose() {
  podman-compose --file compose.yaml $*
}

compose-dev() {
  compose --file dev/compose.yaml $*
}

down() {
  compose down $*
  compose-dev down $*
}

up() {
  compose up --build $*
}

status() {
  compose-dev ps
}

restart() {
  containers=${*:-api datalogger protocol web}
  compose-dev restart $containers
}

logs() {
  container=${1:-protocol}
  compose-dev logs $container
}

build() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    if [[ "$(podman machine inspect --format {{.State}})" != "running" ]]; then
      podman machine start
    fi
  fi

  compose build $*
}

dev() {
  compose-dev up --build
}

format() {
  black **/**py
}

generate() {
  compose-dev exec protocol \
    python /solar-protocol/venv/core/getRemoteData.py

  compose-dev exec protocol \
    python /solar-protocol/venv/build/viz.py

  compose-dev exec protocol \
    python /solar-protocol/venv/build/html.py DEV
}

shell() {
  container=${1:-protocol}
  compose-dev exec $container /bin/bash
}

init() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    command -v podman >/dev/null 2>&1 || brew install podman
    command -v podman-compose >/dev/null 2>&1 || brew install podman-compose

    podman machine inspect >/dev/null 2>&1 || {
      podman machine init --volume /Users
    }

    if [[ "$(podman machine inspect --format {{.State}})" != "running" ]]; then
      podman machine start
    fi
  elif [[ "$(uname -s)" == "Linux" ]]; then
    if command -v lsb_release >/dev/null; then
      if lsb_release -a | grep --quiet 'Debian\|Ubuntu'; then
        command -v podman >/dev/null || sudo apt-get install --yes podman
        command -v pip >/dev/null || sudo apt install --yes python3-pip
        command -v podman-compose >/dev/null || pip install podman-compose

      grep --quiet '/home/pi/.local/bin' /home/pi/.bashrc \
        || echo 'export PATH=$PATH:/home/pi/.local/bin' >> /home/pi/.bashrc

      . /home/pi/.bashrc
    fi
  elif command -v raspi-config >/dev/null; then
    if grep --quiet 'bookworm\|testing' /etc/apt/sources.list; then
    else
      prompt "Upgrade Raspberry Pi OS to bookworm?" 
    fi
  else
    echo See the official windows install docs to install podman and podman-compose
    echo
    echo https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md
  fi

  if [[ -f ~/.bashrc ]]; then
    if ! grep --quiet solar-protocol ~/.bashrc; then
      prompt "Add solar-protocol to bash PATH?" && echo "export PATH=\$PATH:$PWD" >> ~/.bashrc
    fi
  fi

  if [[ -f ~/.zshrc ]]; then
    if ! grep --quiet solar-protocol ~/.zshrc; then
      prompt "Add solar-protocol to zsh PATH?" && echo "export PATH=\$PATH:$PWD" >> ~/.zshrc
    fi
  fi

  command -v podman >/dev/null 2>&1 && command -v podman-compose >/dev/null 2>&1 \
    && echo podman and podman-compose found, init complete!
}

[[ -z "$1" ]] && help

command=$1
shift

case $command in
  up) up ;;
  down) down $* ;;
  restart) restart $* ;;
  logs) logs $* ;;
  init) init ;;
  build) build $*;;
  shell) shell ;;
  dev) dev ;;
  open) open http://127.0.0.1:11221 || xdg-open http://127.0.0.1:11221 ;;
  format) format ;;
  status) status $* ;;
  "") help ;;
  *) help ;;
esac

