#!/usr/bin/env bash

if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi

CI=${CI-false}
command="${1-help}"
shift
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

set -o errexit
set -o nounset

help() {
  Clear='\033[0m'
  Blue='\033[0;34m'

  echo -e "$(
  cat << HELP

  ☀️ solar-protocol - commandline tool to help manage your server

    ${Blue}solar-protocol install${Clear}               install dependencies and completions
    ${Blue}solar-protocol start${Clear}                 start the protocol
    ${Blue}solar-protocol logs api${Clear}              show api logs
    ${Blue}solar-protocol status${Clear}                check status of the containers
    ${Blue}solar-protocol restart datalogger${Clear}    restart the datalogger
    ${Blue}solar-protocol stop${Clear}                  stop all services
    ${Blue}solar-protocol shell protocol${Clear}        open a shell in the protocol container
    ${Blue}solar-protocol update-dns [password]${Clear} update the dns for beta.solarprotocol.net
HELP
  )"
}

exists() {
  command -v "$@" >/dev/null 2>&1
}

platform() {
  if exists raspi-config; then
    echo "pi"
  elif [[ "$(uname -s)" == "Darwin" ]]; then
    echo "mac"
  elif grep -qi microsoft /proc/version; then
    echo "win"
  elif [[ -f /etc/debian_version ]]; then
    echo "debian"
  elif [[ "$(uname -s)" == "Linux" ]]; then
    echo "linux"
  fi
}

PLATFORM=$(platform)

prompt() {
  if [[ "$CI" != "true" ]]; then 
    read -r -p "$* (y/N) " confirm && \
      [[ $confirm == [yY] || $confirm == [yY][eE][sS ]] \
      || exit 1
  fi
}

update-dns() {
  LOGFILE=namecheap.log
  HOST=beta
  DOMAIN=solarprotocol.net
  PASSWORD=$1
  DDNS=https://dynamicdns.park-your-domain.com

  # Get current time
  TIME=$(date +%Y-%m-%d:%H:%M)
  echo "TIME: $TIME"

  # Get current IP
  IP=$(curl --insecure --silent "${DDNS}/getip")
  echo "IP: $IP"

  # Update Namecheap DDNS
  RESPONSE=$(curl --insecure --silent "${DDNS}/update?host=${HOST}&domain=${DOMAIN}&password=${PASSWORD}&ip=${IP}")
  echo "RESPONSE: "
  echo "$RESPONSE"

  # Log the time and IP
  echo "$TIME - $IP" >> $LOGFILE
}

# FIXME: migrate to podman when bookworm is released for raspberry pi
install-docker-debian() {
  sudo apt-get update
  exists docker || sudo apt-get install --yes docker.io
  exists htpasswd || sudo apt-get install --yes apache2-utils

  # Not sure why buildkit fails
  if ! test -f /etc/profile.d/disable-buildkit.sh; then
    echo "export DOCKER_BUILDKIT=0" | sudo tee /etc/profile.d/disable-buildkit.sh > /dev/null

    echo "please run: "
    echo ". /etc/profile.d/disable-buildkit.sh"
  fi

  if ! docker compose >/dev/null; then
    sudo apt-get install --yes ca-certificates curl gnupg lsb-release
    sudo mkdir -p /etc/apt/keyrings
    if ! test -f /etc/apt/keyrings/docker.gpg; then
      curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    fi
    if ! test -f /etc/apt/sources.list.d/docker.list; then
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
        | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    fi

    sudo apt update
    sudo apt-get install --yes docker-compose-plugin
  fi
}

install() {
  if [[ -f ~/.bashrc ]]; then
    if ! grep --quiet solar-protocol ~/.bashrc; then
     if prompt "Add solar-protocol PATH to ~/.bashrc?"; then
       echo "export PATH=\$PATH:$PWD" >> ~/.bashrc
       echo "please run:"
       echo ". ~/.bashrc"
     fi
    fi
  fi

  if [[ -f ~/.zshrc ]]; then
    if ! grep --quiet solar-protocol ~/.zshrc; then
      if prompt "Add solar-protocol PATH and completions to ~/.zshrc?"; then
        echo "export PATH=\$PATH:$PWD" >> ~/.zshrc
        echo "fpath+=($PWD/dev); compinit" >> ~/.zshrc
        echo "please run:"
        echo ". ~/.zshrc"
      fi
    fi
  fi

  # macOS
  if [[ "$PLATFORM" == "mac" ]]; then
    if exists podman; then brew upgrade podman; else brew install podman; fi
    exists podman-compose || pip install https://github.com/containers/podman-compose/archive/devel.tar.gz

    podman machine inspect >/dev/null 2>&1 || podman machine init
    [[ "$(podman machine inspect --format '{{.State}}')" == "running" ]] || podman machine start
    return
  fi

  # raspberry pi OS
  if [[ "$PLATFORM" == "pi" ]] || [[ "$PLATFORM" == "debian" ]]; then
    install-docker-debian

    echo "solar-protocol dependencies installed! try:"
    echo "  solar-protocol build"
    echo "  solar-protocol start"
    return
  fi

  # windows
  if [[ "$PLATFORM" == "win" ]]; then
    echo See the official windows install docs to install podman and podman-compose
    echo
    echo https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md
    return
  fi

  exists docker || exists podman podman-compose
}

generate-key() { openssl rand -hex 16; }

bcrypt() { htpasswd -bnBC 10 "" "$1" | tr -d ':\n'; }

reset() {
  compose down
  if exists podman; then
    podman machine stop
    podman machine rm podman-machine-default
  fi
  install
  if exists podman; then
    podman machine start
  fi
}

# Since we have multiple collaborators, its useful to have all the tabs and spaces align
# Run format before making a pull request to help us all focus on the code changes, and
# not the formatting
format() {
  shopt -s globstar
  black -- **/**.py
  shellcheck solar-protocol
  #tidy -i -m -w 160 -ashtml -utf8 -- **/**.html
}

compose() {
  if [[ "$PLATFORM" == "mac" ]]; then
    machine
    podman-compose --file compose.yaml "$@"
  else
    docker compose --file compose.yaml "$@"
  fi
}

# Before we can run any of the services (web, api, protocol, datalogger), we
# need to build a system 'image', which contains a snapshot of the current code
# and dependencies.
# SystemD is how linux systems run services
# A service is just any software that you want to run every time the system is on
# Raspberry Pis use linux, so this will make sure solar protocol is installed and running at boot
install-systemd() {
  servicedir=$HOME/.config/systemd/user
  mkdir -p "$servicedir"
  cd "$servicedir"
  for service in datalogger api protocol web; do
    servicename=solar-protocol_${service}_1
    filename=container-$servicename.service
    if ! test -f $filename; then
      podman generate systemd --new --files --name $servicename
    fi
    systemctl --user daemon-reload
    if ! systemctl --user is-active $filename; then
      systemctl --user enable $filename
      systemctl --user start $filename
    fi
  done
}

set-admin-password() {
  user=$1
  wanted_password=$2
  password_hash=$(bcrypt "$wanted_password")
  grep -v "^${user}" local/admin.htpasswd > temp.htpasswd
  echo "${user}:${password_hash}" >> temp.htpasswd
  mv temp.htpasswd local/admin.htpasswd
}

case $command in
  up|start) compose up "$@" ;;
  down|stop) compose down "$@" ;;
  status) compose ps 2>/dev/null ;;
  restart) compose restart "${@:-api datalogger protocol web}" ;;
  logs) compose logs "${@:-protocol}" ;;
  build) compose build "$@" ;;
  shell) compose exec "${1:-protocol}" /bin/bash ;;
  open) open http://127.0.0.1:11221 || xdg-open http://127.0.0.1:11221 ;;
  format) format ;;
  run) compose run "$@" ;;
  generate-key) generate-key ;;
  update-dns) update-dns "$@" ;;
  hash) bcrypt "$1" ;;
  install-systemd) install-systemd ;;
  copy-ssh-key) ssh-keygen -ted25519 -f ~/.ssh/solar-protocol-pi | tee | pbcopy ;;
  set-admin-password) set-admin-password "$@" ;;
  reset) reset ;;
  install) install ;;
  *) help ;;
esac

