#!/usr/bin/env bash

if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi

CI=${CI-false}
command="${1-help}"
shift
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

set -o errexit
set -o nounset

test -f local/secrets.json || echo '{}' > local/secrets.json

help() {
  Clear='\033[0m'
  Bold='\033[4m'
  Cyan='\033[0;36m'
  Red='\033[0;31m'
  Green='\033[0;32m'
  Color=$Cyan

  echo -e "$(
  cat << HELP

  ☀️ solar - commandline tool to help manage your server

    solar <${Color}command${Clear}> [${Green}service${Clear}]    where service is one of ${Green}api${Clear}, ${Green}datalogger${Clear}, ${Green}web${Clear}, or ${Green}protocol${Clear}

    solar ${Color}help${Clear}                   show this help

    solar ${Color}open${Clear}                   open the local running site
    solar ${Color}docs${Clear}                   browse the complete solar protocol documentation

    solar ${Color}format${Clear}                 format all the source code

    solar ${Color}battery${Clear}                show the current battery percentage
    solar ${Color}update-dns${Clear} ${Red}password${Clear}    update the dns for beta.solarprotocol.net
    solar ${Color}get-dns-hash${Clear}           create a hash to share with administrators when joining
    solar ${Color}set-admin-password${Clear} ${Red}password${Clear}  update the ${Red}password${Clear} for the admin settings pages
HELP
  )"
}


exists() {
  command -v "$@" >/dev/null 2>&1
}

prompt() {
  if [[ "$CI" != "true" ]]; then 
    read -r -p "$* (y/N) " confirm && \
      [[ $confirm == [yY] || $confirm == [yY][eE][sS ]] \
      || exit 1
  fi
}

update-dns() {
  LOGFILE=namecheap.log
  HOST=beta
  DOMAIN=solarprotocol.net
  PASSWORD=$1
  DDNS=https://dynamicdns.park-your-domain.com

  # Get current time
  TIME=$(date +%Y-%m-%d:%H:%M)
  echo "TIME: $TIME"

  # Get current IP
  IP=$(curl --insecure --silent "${DDNS}/getip")
  echo "IP: $IP"

  # Update Namecheap DDNS
  RESPONSE=$(curl --insecure --silent "${DDNS}/update?host=${HOST}&domain=${DOMAIN}&password=${PASSWORD}&ip=${IP}")
  echo "RESPONSE: "
  echo "$RESPONSE"

  # Log the time and IP
  echo "$TIME - $IP" >> $LOGFILE
}

_generate-key() {
  openssl rand -hex 16
}

bcrypt() {
  htpasswd -bnBC 10 "" "$1" | tr -d ':\n'
}

# Since we have multiple collaborators, its useful to have all the tabs and spaces align
# Run format before making a pull request to help us all focus on the code changes
format() {
  if exists podman; then
    podman run --rm --volume "$(pwd)":/src --workdir /src \
    pyfound/black:latest_release \
    black .
  elif exists docker; then
    docker run --rm --volume "$(pwd)":/src --workdir /src \
    pyfound/black:latest_release \
    black .
  fi

  if exists ruff; then
    ruff check --fix .
  fi

  if exists shellcheck; then
    shellcheck solar
  fi
}

set-admin-password() {
  user=$1
  wanted_password=$2
  password_hash=$(bcrypt "$wanted_password")
  grep -v "^${user}" local/admin.htpasswd > temp.htpasswd
  echo "${user}:${password_hash}" >> temp.htpasswd
  mv temp.htpasswd local/admin.htpasswd
}

_set-dnskey() {
  secret=$1

  tmp=$(mktemp)
  jq --arg secret "$secret" '.dnskey |= $secret' local/secrets.json > "$tmp" \
    && mv "$tmp" local/secrets.json
}

get-dns-hash() {
  tmp=$(mktemp)
  dnskey=$(jq -r '.dnskey' < local/secrets.json)

  if [[ "$dnskey" == "null" ]]; then
    dnskey=$(_generate-key)
    _set-dnskey "$dnskey"
  fi

  dnskey=$(jq -r '.dnskey' < local/secrets.json)
  if [[ "$dnskey" != "null" ]]; then
    bcrypt "$dnskey"
    echo
  fi
}

battery() {
  exists figlet || sudo apt-get install --yes figlet
. $HOME/venv/bin/activate
python -c 'from pymodbus.client import ModbusSerialClient
client=ModbusSerialClient(method="rtu", port="/dev/ttyUSB0", baudrate=115200)
client.connect()
battery=client.read_input_registers(0x311A, 2, 1)
print(battery.registers[0])
'
}

case $command in
  open) open http://127.0.0.1:11221 || xdg-open http://127.0.0.1:11221 ;;
  format) format ;;
  update-dns) update-dns "$@" ;;
  set-admin-password) set-admin-password "$@" ;;
  get-dns-hash) get-dns-hash ;;
  battery) battery ;;
  *) help ;;
esac

