#!/usr/bin/env bash

shift
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null
set -o errexit
set -o nounset

# Override if our mac detection fails
MAC=${MAC:-$(../scripts/get-mac-address)}

# shellcheck source=/dev/null
. ../venv/bin/activate
python3 run.py
