#!/bin/bash

podman run \
  --rm --interactive --tty \
  --name solar-protocol-dev \
  --mount type=bind,src="$(pwd)",target=/solar-protocol \
  --publish 80 \
  localhost/solar-protocol \
  service apache2 start
