#!/bin/bash
set -e

# make sure script works when called from any directory
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

if [[ "$(uname -s)" == "Darwin" ]]; then
  if [[ "$(podman machine inspect --format {{.State}})" != "running" ]]; then
    podman machine start
  fi
fi

podman-compose up --build
