#!/bin/bash
set -e

# make sure script works when called from any directory
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

echo building images...

podman build \
  --file ../charge-controller/Containerfile \
  --format docker \
  --tag solar-protocol/charge-controller ..

podman build \
  --file ../api/Containerfile \
  --format docker \
  --tag solar-protocol/api ..

podman build \
  --file ../protocol/Containerfile \
  --format docker \
  --tag solar-protocol/protocol ..
