#!/bin/bash
set -e

# make sure script works when called from any directory
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

build() {
  image=$1; echo building $image
  cd ../$image && podman build --tag solar-protocol/$image .
}

case $1 in
  api) build api ;;
  charge-controller) build charge-controller ;;
  protocol) build protocol ;;
  "") build api && build charge-controller && build protocol ;;
  *) echo "Unknown container image $1, try api, charge-controller, or protocol" ;;
esac
