SHELL ["/bin/bash", "-c"]
FROM python:3.10
ENV TERM xterm-256color

# Insall apache and php
RUN apt update && apt upgrade --yes && apt install apache2 php php-gd --yes

COPY requirements.txt /home/pi/solar-protocol/requirements.txt
WORKDIR /home/pi/solar-protocol
RUN pip install --no-cache-dir --requirement requirements.txt
COPY . /home/pi/solar-protocol

# Configure apache2 to use our root directory
RUN sed --in-place \
  --expression='s|DocumentRoot /var/www/html|DocumentRoot /home/pi/solar-protocol/frontend|' \
  /etc/apache2/sites-available/000-default.conf

RUN echo '\
<Directory /home/pi/solar-protocol/frontend>\n\
  Options Indexes FollowSymLinks\n\
  AllowOverride All\n\
  Require all granted\n\
  Header set Access-Control-Allow-Origin "*"\n\
</Directory>\n'\
>> /etc/apache2/apache2.conf

# Enable server status interface
RUN sed --in-place \
  --expression='/<\/VirtualHost>/s|^|\n\
<Location /server-status>\n\
SetHandler server-status\n\
Require all granted\n\
</Location>\n|' /etc/apache2/sites-enabled/000-default.conf

RUN echo 'www-data ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers

# Enable CORS and redirection
RUN a2enmod headers && a2enmod rewrite

EXPOSE 80

RUN apt install neovim --yes

CMD apachectl -D FOREGROUND
