SHELL ["/bin/bash", "-c"]
FROM solar-protocol
ENV TERM xterm-256color

RUN apt update && apt upgrade --yes && apt install curl entr imagemagick jq php-cs-fixer ripgrep --yes
RUN pip3 install --upgrade black

CMD bash dev/test-watch
