version: '3.7'

name: solar-protocol

services:
  datalogger:
    environment:
      - DEV=true
    volumes:
      - ../datalogger:/datalogger/venv
  api:
    image: solar-protocol/api
    volumes:
      - ../api:/api/venv
    command: uvicorn api:app --proxy-headers --host 0.0.0.0 --port 80 --reload
  protocol:
    command: python run.py now
    volumes:
      - ../protocol:/protocol/venv
