#!/bin/bash
set -e

# make sure script works when called from any directory
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

container=solar-protocol
root=/home/pi/solar-protocol

data() {
  podman exec --interactive --tty $container \
    python $root/backend/core/getRemoteData.py
}

viz() {
  podman exec --interactive --tty $container \
    python $root/backend/createHTML/viz.py
}

html() {
  podman exec --interactive --tty $container \
    python $root/backend/createHTML/create_html.py DEV
}

case $1 in
  data) data ;;
  viz) viz ;;
  html) html ;;
  "") data && viz && html ;;
  *) echo "Unknown generator $1, try data, viz, or html" ;;
esac

