#!/bin/bash
set -e

# make sure script works when called from any directory
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

containers=${*:-api charge-controller solar-protocol}
echo restarting $containers

podman-compose --file compose.yaml --file dev.compose.yaml restart $containers

bash stop
