#!/bin/bash
# rebuild the image if the Containerfile changes

# script works from any directory
cd "$(dirname "$(readlink -f "$0")")"

ls Containerfile | entr -c -a -s 'bash build-image && tput bel; tput bel; tput bel'
