#!/bin/bash
set -e

# make sure script works when called from any directory
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

echo starting solar-protocol

podman-compose up

down() { podman-compose down; }

trap down SIGHUP SIGINT SIGQUIT SIGABRT
