#!/bin/bash
set -e

# make sure script works when called from any directory
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

fd --extension py --extension html --extension js --extension sh --extension css . ..\
  | entr -c bash test
