#!/bin/bash
set -e

# make sure script works when called from any directory
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

warn() {
  echo $*
  exit
}

command -v compare >/dev/null || warn "'compare' command not found, please install imagemagick"

rm -f temp/*
bash ../utilities/updateDeviceList.sh
bash ../dev/generate data
bash ../dev/generate viz

cp ../backend/createHTML/viz-assets/clock.png temp/actual.png 
curl --silent solarprotocol.net/images/clock.png > temp/expected.png

compare -metric AE temp/expected.png temp/actual.png null || {
  compare -compose src temp/expected.png temp/actual.png temp/diff.png
  open temp/diff.png
  echo 1
}
