#!/bin/bash
percent=$("$HOME"/solar-protocol/solar battery)
big=$(toilet --filter gay --font ivrit --width 28 "${percent} %")

read -r -d '' sun << EOM
      ;   :   ;
   .   \_,!,_/   ,
    `.,'     `.,'
     /         \
~ -- :         : -- ~
     \         /
    ,'`._   _.'`.
   '   / `!` \   `
      ;   :   ;      
EOM

paste \
  <(echo "$sun") \
  <(echo; echo; echo "$big") 
