FROM localhost/solar-protocol/base:latest

RUN apt-get --quiet install \
  build-essential libcairo2 libffi-dev \
  libjpeg-dev zlib1g zlib1g-dev --yes

WORKDIR /solar-protocol
RUN python -m venv /solar-protocol/venv
ENV PATH="/solar-protocol/venv/bin:$PATH"
RUN pip install --quiet --no-cache-dir wheel
COPY requirements.txt .
RUN pip install --quiet --no-cache-dir --requirement requirements.txt
RUN pip install /common

WORKDIR /solar-protocol/venv
COPY . .

CMD python run.py
