FROM python:3.10-slim

RUN apt-get --quiet update && apt-get --quiet upgrade --yes && apt-get --quiet install libcairo2 --yes
ENV TERM=screen-256color

WORKDIR /solar-protocol
RUN python -m venv /solar-protocol/venv
ENV PATH="/solar-protocol/venv/bin:$PATH"
COPY requirements.txt .
RUN pip install --quiet --no-cache-dir --requirement requirements.txt

WORKDIR /solar-protocol/venv
COPY . .

CMD python run.py
