#!/usr/bin/env bash

shift
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null
set -o errexit
set -o nounset

# shellcheck source=/dev/null
. ../../venv/bin/activate
python3 -m uvicorn .:app --proxy-headers --host 0.0.0.0 --port 7676 --reload
