#!/usr/bin/env bash

shift
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null
set -o errexit
set -o nounset

PLATFORM=${PLATFORM:-$(./platform)}

if [[ "$PLATFORM" == "pi" ]]; then
  cat /sys/class/net/wlan0/address
elif [[ "$PLATFORM" == "mac" ]]; then
  ifconfig en0 | awk '/ether/{print $2}'
elif [[ "$PLATFORM" == "debian" ]]; then
  ifconfig eth0 | awk '/ether/{print $2}'
elif [[ "$PLATFORM" == "linux" ]]; then
  ifconfig eth0 | awk '/ether/{print $2}'
fi
