#!/usr/bin/env bash

shift
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null
set -o errexit
set -o nounset

if [[ ! -d ../../venv ]]; then
  python3 -m venv ../../venv
fi

# shellcheck source=/dev/null
. ../../venv/bin/activate

python3 -m pip install \
  --requirement ../../src/common/requirements.txt \
  --requirement ../../src/api/requirements.txt \
  --requirement ../../src/datalogger/requirements.txt \
  --requirement ../../src/protocol/requirements.txt \
  --quiet
