#!/usr/bin/env bash

shift
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null
set -o errexit
set -o nounset

install -d -m 700 ~/.ssh
sudo mv ../utilities/authorized_keys /home/pi/.ssh/authorized_keys
sudo chmod 644 /home/pi/.ssh/authorized_keys
sudo chown pi:pi /home/pi/.ssh/authorized_keys
