#!/bin/bash

python3 -m pip install --upgrade venv
python3 -m venv venv
. venv/bin/activate

for service in api common datalogger protocol; do
  python3 -m pip install \
    --user --quiet --no-cache-dir \
    --requirement ${service}/requirements.txt
done
