FROM localhost/solar-protocol/base:latest
RUN apt-get --quiet update && apt-get --quiet upgrade --yes

WORKDIR /datalogger
RUN python -m venv /datalogger/venv
ENV PATH="/datalogger/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --quiet --no-cache-dir --requirement requirements.txt
RUN pip install --quiet --no-cache-dir /common

WORKDIR /datalogger/venv
COPY csv_datalogger.py .

CMD python csv_datalogger.py
