#!/usr/bin/env bash

shift
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null
set -o errexit
set -o nounset

# Run with FAKE_DATA=True to fake the data
FAKE_DATA=${FAKE_DATA:-False}

# We detect 
PLATFORM=${PLATFORM:-unknown}

if [[ $PLATFORM == unknown ]]; then
  PLATFORM=$(../scripts/platform)
fi

# shellcheck source=/dev/null
. ../venv/bin/activate
python3 csv_datalogger.py
