#!/usr/bin/env bash

# this script will install solar protocol as a systemd service

# set current working directory to the same as this file 
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

set -o errexit
set -o nounset

if ! systemd-notify --booted; then
  echo "Script only meant to be run on a systemd managed system" >&2
  exit 1
fi 

project_directory=$(realpath ${PWD}/../..)
unit_path=/etc/systemd/system
service_path="$unit_path"/solar-protocol.service

echo "installing systemd service to $service_path"
cat <<EOF | sudo tee "$service_path" >/dev/null
# $service_path

[Unit]
Description=Solar Protocol

[Service]
Type=simple
WorkingDirectory=${project_directory}
ExecStart=${project_directory}/start.sh
User=$USER

[Install]
WantedBy=multi-user.target
EOF

echo "(re)loading solar-protocol.service"
sudo systemctl daemon-reload

echo "stopping if active"
if systemctl is-active solar-protocol; then
  sudo systemctl stop solar-protocol
fi

echo "enabling if disabled"
if ! systemctl is-enabled solar-protocol; then
  sudo systemctl enable solar-protocol
fi

echo "starting solar-protcool"
if ! systemctl is-active solar-protocol; then
  sudo systemctl start solar-protocol
fi

echo 'printing status with `systemctl status solar-protocol`'
systemctl status solar-protocol
